### PR TITLE
Karma design

### PR DESCRIPTION
**Pull request by karoluzas**
Been working on this for quite a while now
What's changed:
- Main pages redesigned (Index/Submits/Requests)
- Login and Register page also a bit changed

Item, error page, and etc. are still in the works. Need more inspiration to figure out how to make them work, especially the items page. 
I'm lookin forward to some feedback and ideas on how to change certain things (if needed). 
Enjoy trying the changes out, don't hesitate to point out things I missed to fix/include.

### CODE REVIEW

**Review by disoversity — CHANGES_REQUESTED** [review]
Finally, our web app some identity (at least looking at the design :D). Times New Roman font is indeed a **bold** choice, while the font and the design overall may look weird in the context of other modern, cyberpunky web designs, I feel that this new design is welcoming and somewhat nostalgic. However, after fiddling around with window resizes, I think some areas of text get too big (e. g. submit item/request buttons get very very big). Another thing, on smaller window sizes, the submits and requests navigation buttons disappear, which made me confused for a little bit. That being said, apart from these problems, the changes made by you are refreshing. I hope we could hear everyone else's word on this,.

**Comment by disoversity** [comment]
image

**Comment by karoluzas** [comment]
> Finally, our web app some identity (at least looking at the design :D). Times New Roman font is indeed a **bold** choice, while the font and the design overall may look weird in the context of other modern, cyberpunky web designs, I feel that this new design is welcoming and somewhat nostalgic. However, after fiddling around with window resizes, I think some areas of text get too big (e. g. submit item/request buttons get very very big). Another thing, on smaller window sizes, the submits and requests navigation buttons disappear, which made me confused for a little bit. That being said, apart from these problems, the changes made by you are refreshing. I hope we could hear everyone else's word on this,.

As for the Times New Roman font that shouldn't happen, I specifically used Roboto font and it works on my end, will research why it dose that.
The submit 'buttons' are that big because they not only serve a button function but also as a header for the page, well at least that was my idea at first :D would like to see what others think.
And yes and I will fix the resizing of the buttons, completely forgot about mobile side of website while developing. 
If u resize to a window of ~500px then the buttons do disappear on the nav bar, but there actually is a button in the corner that you can press. It's a bootstrap thing that makes it a collapsable, but for some reason it's not working, and it's not working for quite some time now, but yes thank you for bringing that up will need to figure something out.

I'll probably push the changes tomorrow because it is kind of late and need to revise for a test for tmrw.

Many thanks for the feedback

**Comment by karoluzas** [comment]
@disoversity try out the recent commit to see if it works alright

**Comment by disoversity** [comment]
Basically everything I mentioned was fixed 👍 The font is not Times New Roman anymore (although I kind of liked it). The submit and request buttons are smaller on resizes. The collapsible menu/navbar options finally appears... So far so good, and I like it 👍 Time for me to get some work done as well 😎 Going to look into our issues with entity framework

**Comment by disoversity** [comment]
I think we are ready for the merge... or shall we wait for other's feedback?

**Review by disoversity — APPROVED** [review]

**Comment by karoluzas** [comment]
doesn't look like  anyone will review this, let's merge

**Comment by disoversity** [comment]
Alright, let's do it.

**Pull request merged**
