### PR TITLE
Add feature karmapoints

### PR DESCRIPTION
**Pull request by bamboozlegui**
Hello yall, here is a simple implementation of Karma Point system with delegate use.
I'm not sure if adding logic in KarmaUser class is a good idea, so if you have any suggestions, I'd appreciate it.

### CODE REVIEW

**Comment by karoluzas** [comment]
Is there a database entry made for KarmaPoints and if there is will we need to drop database ?

**Comment by bamboozlegui** [comment]
> 
> 
> Is there a database entry made for KarmaPoints and if there is will we need to drop database ?

Glad you asked, yeah there actually is a new property to KarmaUser class, so it was added to the database. You should drop and update databases.

**Comment by disoversity** [comment]
I think it is fine to have some methods and delegates in a Model class since it does not change the model itself, but adds additional functionality. However, I think we should put this karma point giving logic to a separate class, so we would not repeat the same code in future post types or any other Karma rewarding activities. Additionally, a separate class could listen to events.

**Comment by bamboozlegui** [comment]
> 
> 
> I think it is fine to have some methods and delegates in a Model class since it does not change the model itself, but adds additional functionality. However, I think we should put this karma point giving logic to a separate class, so we would not repeat the same code in future post types or any other Karma rewarding activities. Additionally, a separate class could listen to events.

Alright, will work on that in the future.

**Pull request merged**
